# ===================================================
# meta infos
# ===================================================
meta:
  project: kyt
  include:
    - dobi.yaml
    - version.yaml
    - eventhub2db/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=build:
  tasks:
    - build-eventhub2db
    - image-eventhub2db
  annotations:
    description: "[alias] build all"
    tags:
      - alias

alias=deploy:
  tasks:
    - image-eventhub2db:push
  annotations:
    description: "[alias] push all"
    tags:
      - alias
