resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: teliaoss/github-pr-resource

resources:
  - name: pull-request
    type: pull-request
    check_every: 30s
    webhook_token: ((webhook_token))
    source:
      repository: ci4rail/ads-demo-environment
      access_token: ((access_token))

  - name: image-golang
    type: docker-image
    source:
      repository: golang
      tag: 1.16-buster

jobs:
  - name: build
    plan:
      - get: image-golang

      - get: pull-request
        trigger: true
        version: every

      - put: pull-request
        params:
          path: pull-request
          status: pending

      - in_parallel:
          - task: build-eventhub2db
            image: image-golang
            config:
              platform: linux
              inputs:
                - name: pull-request
              outputs:
                - name: install
              run:
                path: /bin/bash
                args:
                  - -ec
                  - |
                    ROOT=$(pwd)
                    cd ${ROOT}/pull-request/eventhub2db
                    make test
                    make
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

          - task: build-eventhub2db-image
            privileged: true
            config:
              platform: linux
              image_resource:
                type: registry-image
                source:
                  repository: vito/oci-build-task
              inputs:
                - name: pull-request
              outputs:
                - name: image
              run:
                path: build
              params:
                CONTEXT: pull-request/
                DOCKERFILE: pull-request/eventhub2db/Dockerfile
            on_failure:
              put: pull-request
              params:
                path: pull-request
                status: failure

      - put: pull-request
        params:
          path: pull-request
          status: success
