{
 "title": "GPS Demo",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "GPS Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n((data->>'lat')::numeric) as value,\n\"time\" as \"time\" \nFROM \"adsdata\" \nWHERE $__timeFilter(time) ORDER BY time ASC"
    },
    {
     "rawSql": "SELECT\n((data->>'lon')::numeric) as value,\n\"time\" as \"time\" \nFROM \"adsdata\" \nWHERE $__timeFilter(time) ORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Lat",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ((data->>'lat')::numeric) as lat\nFROM adsdata\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Lon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ((data->>'lon')::numeric) as lon\nFROM adsdata\nWHERE\n  $__timeFilter(\"time\")\nORDER BY 1\n"
    }
   ]
  }
 ]
}