{
 "title": "GPS Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPS Location with Fix",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n((data->>'lat')::numeric) as value,\n\"time\" as \"time\" \nFROM \"adsdata\" \nWHERE $__timeFilter(time) AND ((data->>'mode')::numeric) >= 2 ORDER BY time ASC "
    },
    {
     "rawSql": "SELECT\n((data->>'lon')::numeric) as value,\n\"time\" as \"time\" \nFROM \"adsdata\" \nWHERE $__timeFilter(time) AND ((data->>'mode')::numeric) >= 2 ORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ((data->>'lon')::numeric) as lon\nFROM adsdata\nWHERE\n  $__timeFilter(\"time\") AND ((data->>'mode')::numeric) >= 2\nORDER BY 1\n"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ((data->>'lat')::numeric) as lat\nFROM adsdata\nWHERE\n  $__timeFilter(\"time\") AND ((data->>'mode')::numeric) >= 2\nORDER BY 1"
    }
   ]
  },
  {
   "title": "GPS Fix lost",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  ((data->>'mode')::numeric) as mode\nFROM adsdata\nWHERE\n  $__timeFilter(\"time\") AND ((data->>'mode')::numeric) < 2\nORDER BY 1"
    }
   ]
  }
 ]
}